# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "nvme" "usbhid" "sd_mod" "bcache" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f3818b1f-ad35-4331-8379-7e5987f5e4f5";
      fsType = "btrfs";
      options = [ "subvol=@nix" "discard=async" "space_cache=v2" "compress-force=zstd:4" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f3818b1f-ad35-4331-8379-7e5987f5e4f5";
      fsType = "btrfs";
      options = [ "subvol=@home" "discard=async" "space_cache=v2" "compress-force=zstd:4" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B10A-B619";
      fsType = "vfat";
    };

  fileSystems."/home/atila/Games" =
    { device = "/dev/disk/by-uuid/111c9c9a-130f-4840-be07-5a6414cd5296";
      fsType = "btrfs";
      options = [ "subvol=@games" "autodefrag"  "compress-force=zstd:2" "space_cache=v2" ];
    };

  fileSystems."/home/atila/Games/nvme" =
    { device = "/dev/disk/by-uuid/f3818b1f-ad35-4331-8379-7e5987f5e4f5";
      fsType = "btrfs";
      options = [ "subvol=@games" "nofail" "discard=async" "space_cache=v2" "compress-force=zstd:4" ];
    };

  fileSystems."/home/atila/Files" =
    { device = "/dev/disk/by-uuid/2d116175-d8cf-4b70-bb02-1e57927cc982";
      fsType = "btrfs";
      options = [ "subvol=@files" "autodefrag" "nofail" "space_cache=v2" "compress-force=zstd:9" ];
    };
  fileSystems."/home/atila/Files/storage" =
    { device = "/dev/disk/by-uuid/111c9c9a-130f-4840-be07-5a6414cd5296";
      fsType = "btrfs";
      options = [ "subvol=@storage" "autodefrag" "nofail" "space_cache=v2" "compress-force=zstd:2" ];
    };

  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/34081a37-6fb1-418a-9d88-427d1e866d6c";
      fsType = "btrfs";
      options = [ "subvol=storage"  "autodefrag" "nofail" "space_cache=v2" "compress=lzo" ];
    };

  #swapDevices =
    #[ {
            #device = "/dev/disk/by-uuid/40d39eb7-4297-4e6a-8055-814f99f3b055";
            #priority = 5;
      #}
    #];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
