# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/29939feb-19e3-45fe-8daa-007695d02dc6";
      fsType = "btrfs";
      options = [ "subvol=@nixos" "compress=zstd" "autodefrag" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0729-D994";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/29939feb-19e3-45fe-8daa-007695d02dc6";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "autodefrag" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/29939feb-19e3-45fe-8daa-007695d02dc6";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "autodefrag" "noatime" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/29939feb-19e3-45fe-8daa-007695d02dc6";
      fsType = "btrfs";
      options = [ "subvol=@var" "compress=zstd" "autodefrag" "noatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d64ad374-a931-4367-9cc7-adccc3bd45ee"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
